---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/docker-cpi
    tag: main

inputs:
- name: java-release
- name: jdk
- name: stemcell

outputs:
- name: java-release-out

run:
  path: java-release/ci/build.sh

params:
  BLOBSTORE_ACCESS_KEY_ID:
  BLOBSTORE_SECRET_ACCESS_KEY:
