---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/docker-cpi

inputs:
- name: java-release
- name: jdk
- name: stemcell

outputs:
- name: java-release-out

run:
  path: java-release/ci/build.sh
