---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: java-release
- name: jdk
- name: jre

outputs:
- name: java-release-out

run:
  path: java-release/ci/build.sh